### ISSUE TITLE
Refactor internal API

### ISSUE THREAD

**Issue by MarcBresson** [datategy/Fair-Mango#9]
- remove `pr_to_unp` parameter that is used to sort the ranking outputs. It is easy to sort afterwards once we have the results.
- `.summary()` should not be responsible for the computation. I recommend using `.__call__()`.

**Comment by NacerKROUDIR** [comment]
- Removed `pr_to_unp` parameter.
- Migrated the common computation between `.summary()` and `.rank()` to a new function `._compute()`. I did not use `.__call__()` as it allows the object of the class to be callable. This means we would create another object of the class inside itself which would be complex and not memory efficient.
